# Generated by Django 3.2.13 on 2022-05-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer_type', models.CharField(blank=True, choices=[('text', 'Textbox'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox')], default='text', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False, null=True)),
                ('answertext', models.CharField(blank=True, max_length=255, null=True)),
                ('answers', models.ManyToManyField(null=True, to='fegsurveyapp.Options')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fegsurveyapp.question')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fegsurveyapp.survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fegsurveyapp.survey'),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fegsurveyapp.question'),
        ),
    ]
