# Generated by Django 3.2.13 on 2022-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('text', 'Textbox'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('date', 'Date')], default='text', max_length=64, null=True),
        ),
    ]
