# Generated by Django 3.2.13 on 2022-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
