# Generated by Django 3.2.13 on 2022-05-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0003_auto_20220525_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
