# Generated by Django 3.2.13 on 2022-05-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0004_answers_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('text', 'Textbox'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox')], max_length=64, null=True),
        ),
    ]
