# Generated by Django 3.2.13 on 2022-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0006_auto_20220526_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.ManyToManyField(null=True, to='fegsurveyapp.Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('text', 'Textbox'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox')], default='text', max_length=64, null=True),
        ),
    ]
