# Generated by Django 3.2.13 on 2022-05-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0007_auto_20220527_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fegsurveyapp.answers'),
        ),
    ]
