# Generated by Django 3.2.13 on 2022-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0008_auto_20220527_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.ManyToManyField(null=True, to='fegsurveyapp.Answers'),
        ),
    ]
