# Generated by Django 3.2.13 on 2022-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0010_auto_20220527_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyentry',
            name='answers',
            field=models.ManyToManyField(null=True, to='fegsurveyapp.Answers'),
        ),
    ]
