# Generated by Django 3.2.13 on 2022-05-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fegsurveyapp', '0011_surveyentry_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
